# Generated by Django 5.2.13 on 2026-04-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('cover', models.ImageField(upload_to='books/')),
                ('file', models.FileField(upload_to='books/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
