# Generated by Django 5.2.13 on 2026-05-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='companies',
            field=models.ManyToManyField(to='horse_tour.tourcompany'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.person'),
        ),
        migrations.DeleteModel(
            name='CompanyService',
        ),
    ]
