# Generated by Django 5.2.13 on 2026-05-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0002_service_companies_alter_horse_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('people_count', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.tourcompany')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_tour.person')),
            ],
        ),
    ]
