# Generated by Django 5.2.13 on 2026-05-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
