# Generated by Django 5.2.13 on 2026-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcompany',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourcompany',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
